# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default 

variables:
  varTemplateFile: './fortigate/main.bicep'
  varParameterFile: './fortigate/parameters/parameters.bicepparam'
  varDeploymentName: 'fortigate-deployment'
  varLocation: 'switzerlandnorth'
  varResourceGroupName: 'pipeline-test'

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'SVCConnectionConnectivitySub'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az account show