# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  varTemplateFile: './fortigate/main.bicep'
  varParameterFile: './fortigate/parameters/parameters.bicepparam'
  varDeploymentName: 'fortigate-deployment'
  varLocation: 'switzerlandnorth'
  varResourceGroupName: 'pipeline-test'

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    powerShellErrorActionPreference: 'continue'
    azureSubscription: 'SVCConnectionConnectivitySub'
    inlineScript: |
     az group create --name $(varResourceGroupName)  --location $(location)
     az deployment sub create --location $(location) --template-file $(varTemplateFile) --parameters $(varParameterFile)
