# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  varTemplateFile: './fortigate/main.bicep'
  varParameterFile: './fortigate/parameters/parameters.bicepparam'
  varDeploymentName: 'fortigate-deployment'
  varLocation: 'switzerlandnorth'
  varResourceGroupName: 'pipeline-test'

steps:
- task: PowerShell@2
  inputs:
    scriptLocation: 'inlineScript'
    powerShellErrorActionPreference: 'continue'
    azureSubscription: 'SVCConnectionConnectivitySub'
    inlineScript: |
     New-AzSubscriptionDeployment -Name test -Location $(location) -TemplateFile $(varTemplateFile) -TemplateParameterFile  $(varParameterFile)
