# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: 'Pipeline templates'
stages:
- stage: Build
  displayName: 'Securing pipelines with templates'
  jobs:
  - job: Build
    displayName: 'Example Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SVCConnectionConnectivitySub'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Running script using Managed Identity"
          echo "Creating new RG rgfromMi3"
          az group create -g rgfromMi3 -l switzerlandnorth

#          azureResourceManagerConnection: 'SVCConnectionConnectivitySub'
#          subscriptionId: '3e93b848-f45a-4efa-ae91-e508f932bfda'
